version: '3'
services:
  web:
    build: ./nginx
    ports:
      - '8080:80'
    links:
      - php-fpm
    volumes:
      - ./data:/usr/share/nginx/html
  php-fpm:
    build: ./php-fpm
    links:
      - db
    volumes:
      - ./data:/usr/share/nginx/html
  db:
    build: ./mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
       MYSQL_ROOT_PASSWORD: rootpass
       MYSQL_USER: user
       MYSQL_PASSWORD: userpass
       MYSQL_DATABASE: sample
